### ISSUE TITLE
face an error at validate process

### ISSUE THREAD

**Issue by Fulitcher** [retsuh-bqw/SRFormer-Text-Det#19]
I'm currently fine-tuning totaltext ("pretrain_totaltext_ctw.pth" pre-train is loaded)

BTW, An error occurred at the end of the validate process. (training step has no problem)

my test data path is specified at "adet/data/builtin.py"
( "totaltext_poly_test": ("totaltext/test_images", "totaltext/test_poly.json") is using now.)

but, process is trying to load Another GT at "gt_totaltext.zip". why we need "gt_totaltext.zip"?? 
GT is specified at "adet/data/builtin.py"

If I use custom data,
how can I configure my own custom data path??

[Error log]
[12/09 00:26:49 adet.data.datasets.text]: Loaded 300 images in COCO format from /user/data/text_detector_srformer/totaltext/test_poly.json
[12/09 00:26:49 d2.data.build]: Distribution of instances among all 1 categories:
|  category  | #instances   |
|    text    | 1969         |
|            |              |
[12/09 00:26:49 d2.data.dataset_mapper]: [DatasetMapper] Augmentations used in inference: [ResizeShortestEdge(short_edge_length=(1000, 1000), max_size=1800, sample_style='choice')]
[12/09 00:26:49 d2.data.common]: Serializing the dataset using: <class 'detectron2.data.common._TorchSerializedList'>
[12/09 00:26:49 d2.data.common]: Serializing 300 elements to byte tensors and concatenating them all ...
[12/09 00:26:49 d2.data.common]: Serialized dataset takes 0.85 MiB
[12/09 00:26:49 d2.evaluation.evaluator]: Start inference on 75 batches
[12/09 00:26:59 d2.evaluation.evaluator]: Inference done 65/75. Dataloading: 0.0016 s/iter. Inference: 0.0926 s/iter. Eval: 0.0001 s/iter. Total: 0.0944 s/iter. ETA=0:00:00
[12/09 00:27:00 d2.evaluation.evaluator]: Total inference time: 0:00:07.180059 (0.102572 s / iter per device, on 4 devices)
[12/09 00:27:00 d2.evaluation.evaluator]: Total inference pure compute time: 0:00:06 (0.093094 s / iter per device, on 4 devices)
[12/09 00:27:05 adet.evaluation.text_evaluation_det]: Saving results to /user/workspace/SRFormer-Text-Det/output/r_50_poly/totaltext/tune_b4_l40sx4/inference/text_results.json
An invalid detection in temp_det_results/0000006.txt line 7 is removed ... 
An invalid detection in temp_det_results/0000047.txt line 0 is removed ... 
An invalid detection in temp_det_results/0000110.txt line 2 is removed ... 
An invalid detection in temp_det_results/0000127.txt line 0 is removed ... 
An invalid detection in temp_det_results/0000237.txt line 2 is removed ... 
An invalid detection in temp_det_results/0000281.txt line 20 is removed ... 
gtFilePath: datasets/evaluation/gt_totaltext.zip
submFilePath: det.zip
Traceback (most recent call last):
  File "/user/workspace/SRFormer-Text-Det/tools/train_net.py", line 290, in <module>
    launch(
  File "/usr/local/lib/python3.10/site-packages/detectron2/engine/launch.py", line 69, in launch
    mp.start_processes(
  File "/usr/local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 198, in start_processes
    while not context.join():
  File "/usr/local/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/user/workspace/SRFormer-Text-Det/adet/evaluation/rrc_evaluation_funcs_det.py", line 56, in load_zip_file
    archive = zipfile.ZipFile(file, mode='r', allowZip64=True)
  File "/usr/local/lib/python3.10/zipfile.py", line 1249, in __init__
    self.fp = io.open(file, filemode)
FileNotFoundError: [Errno 2] No such file or directory: 'datasets/evaluation/gt_totaltext.zip'

**Comment by retsuh-bqw** [comment]
You should first download the [annotation files](https://1drv.ms/u/s!AtF4kB5K12hqgVr0wHEUD7XzVePw?e=EKcBDC), and put it to corresponding location before initiating evaluation.
